name: Nokwok
main: me.Mattq.NokwokBungee.Main
version: 1.0
author: Mattq

commands:
  server:
    description: Teleports to another server
  s:
    description: sTAFFCHAT
  msg:
    description: Message a player
    aliases: [message]
  discord:
    description: Discord command
  find:
    description: Find a player